Fix #104 - Support PostgreSQL alternative sink
serilog-contrib/serilog-ui pull request #105
Opened 2024-01-16 13:38 UTC by mo-esmp

This PR aims to fix [issue 104](https://github.com/serilog-contrib/serilog-ui/issues/104), to support [Serilog.Sinks.Postgresql.Alternative](https://github.com/serilog-contrib/Serilog.Sinks.Postgresql.Alternative) sink. 
Hence, existing integration tests are according to Serilog.Sinks.PostgresSQL, I added some unit tests (`QueryBuilderTests.cs`) for query generation based on Serilog.Sinks.Postgresql.Alternative. Once we refactored integration tests and used sinks to insert log data, we could unify tests for both sinks.

2024-01-23 19:27 UTC, followynne requested changes
LGTM, just added some nit-picker comments to clean it up but the PR is fine and ready for merge!

About the tests, I think we need integration using the Alternative sink but we can add them later, that's fine  :)

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/Extensions/PostgreSqlDbOptions.cs
I would move it inside Postgres...Provider/Models/ folder, just for clarity :)

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/Extensions/PostgreSqlSinkType.cs
I would move it inside Postgres...Provider/Models/ folder, just for clarity :)

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/PostgreSqlAlternativeSinkColumnNames.cs
As per previous comment, would move inside Postgres...Provider/Models

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/PostgreSqlSinkColumnNames.cs
as per previous comment, would move it inside Postgres...Provider/Models/

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/SinkColumnNames.cs
as per previous comment, would move it inside Postgres...Provider/Models/

2024-01-23 19:27 UTC, followynne commented on src/Serilog.Ui.PostgreSqlProvider/QueryBuilder.cs
> +        ref DateTime? startDate,
out of curiosity, can I ask you the reason to use ref on all 4 Datetimes parameters? I don't think we need it, as Datetime is a struct and shouldn't give us issues without the ref...

2024-01-23 19:27 UTC, followynne commented on tests/Serilog.Ui.PostgreSqlProvider.Tests/DataProvider/DataProviderBaseTest.cs
> +        [Fact(Skip = "No longer needed!")]
We can remove the test, if we don't need to check the null reference :)

2024-01-23 19:27 UTC, followynne commented on tests/Serilog.Ui.PostgreSqlProvider.Tests/Util/PostgresTestProvider.cs
> -//using
we can remove these 2 lines

2024-01-24 08:50 UTC, mo-esmp commented on src/Serilog.Ui.PostgreSqlProvider/QueryBuilder.cs
> +        ref DateTime? startDate,
You're right, just a micro optimization to avoid creating another copy.

2024-01-25 10:08 UTC, mo-esmp commented on tests/Serilog.Ui.PostgreSqlProvider.Tests/DataProvider/DataProviderBaseTest.cs
> +        [Fact(Skip = "No longer needed!")]
Cannot remove it for now because the method is defined in `IUnitBaseTests` interface.

2024-01-25 10:11 UTC, mo-esmp commented
@followynne I applied your comments; please re-review.

2024-01-25 10:17 UTC, followynne approved these changes
@mo-esmp 

all good from my side, I only see we miss the namespace change in the 4 Models/ files (from Provider to Provider.Models)

if you can apply that change, then I'd say let's go 😄

2024-01-26 08:45 UTC, merged