feat(options): Home button url, custom css/js injection, allowing local requests
serilog-contrib/serilog-ui pull request #40
Opened 2022-08-15 16:08 UTC by sommmen

Added:
 - Option in `UIOptions` to supply a custom home button url so that users which operate with different sub-domains can fix the home button (in my case the web api is detached from the frontend server and they're hosted on different domains, so the home button never worked)
 - Option in `AuthorizationOptions` to disable the feature to always exempt local requests from authentication. This way I can test my application locally.
- Option in `UIOptions`  to inject custom CSS / JS in the head of the index.html, just like swagger can. This is the main feature and allows for great customizations, and for me particularly should help with #22.

Changed:
- Added samples of these options in the sample web app, not sure if you'd want to leave those there but it provides a quick way to inspect the results of this feature branch so i left them in.
- Changed the target to net6 for the WebApi since that's the only framework version i've got installed.

Remarks:
- Right now i'm using a dummy meta tag in the head for the custom head content since the dev server with parcel js does not replace the template values
- Feel free to edit and so on - i just need to inject some custom JS if possible.

2022-08-15 16:08 UTC, sommmen commented
@mo-esmp @followynne for review.

2022-08-16 07:30 UTC, mo-esmp commented
Thanks for the PR, I will review it soon.

2022-08-16 20:40 UTC, followynne requested changes
Hello @sommmen,

thanks for the PR and the requested review! I like your proposal, I just put some small ideas in the review - feel free to give it a look and let me know what you think about them.

(the only one I strongly suggest following is to remove the package-lock update from the PR)

I'll let @mo-esmp check the PR & review and provide additionals🙂

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
I really like the idea, my suggestion would be to rewrite the signatures to create 2 methods per injection element, one that adds to HeadContent and one to a new property BodyContent.
It will give greater flexibility to the implementation 😀 

In the end they would become:
_InjectStylesheetAtBodyEnd, InjectJavascriptAtBodyEnd, InjectStylesheetAtHeadEnd, InjectJavascriptAtHeadEnd_

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectJavascript(this UiOptions options, string path, string type = "text/javascript")
```suggestion
        public static UiOptions InjectJavascript(this UiOptions options, string path, string type = "text/javascript")
```
Would you like the idea of returning UiOptions itself, to have a nicer fluent registration of the injections? An alternative could be to provide overloads that accept `params string[] `of paths...

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/Extensions/UiOptions.cs
> +        internal string HeadContent { get; set; } = "";
```suggestion
        internal string HeadContent { get; set; } = string.Empty;
```
sry, just had a couple of sonar-intensive weeks... 🤣

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/assets/index.html
> +            window.config = JSON.parse('{"routePrefix":"serilog-ui","authType":"Jwt"');
Is it correct this change here? I think that parenthesis should be there...

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/package-lock.json
>  {
This updated file can be removed, as you didn't do any packages update 😃  I'd prefer to keep it clean and synced with the latest upgraded version.

2022-08-16 20:40 UTC, followynne commented on src/Serilog.Ui.Web/assets/index.html
>  </body>
```suggestion
         <meta name="dummy" content="%(BodyContent)">
</body>
```
if you like the BodyContent suggestion, I'd add the option here

2022-08-17 10:43 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
I'm currently leaning to leave it as-is it should currently cover all use-cases afaik.

Your suggestions in my mind would only be overhead in terms of library size, maintenance and complexity at that point. In any case it would not be a disaster to add or something so lmk if you really really want this and ill add it in.

2022-08-17 10:47 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectJavascript(this UiOptions options, string path, string type = "text/javascript")
Yeah i was playing with the same idea, but you're accessing the `UIOptions` in a `Action` already so there is no real need to use a fluent API:

``` csharp
app.UseSerilogUi(x =>
{
    x.RoutePrefix = "serilog-ui";
    x.HomeUrl = "/#Test";
    x.InjectJavascript("/js/serilog-ui/custom.js")
});
```

On the other hand i don't see any downfalls so i'll add it in.

2022-08-17 10:50 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/UiOptions.cs
> +        internal string HeadContent { get; set; } = "";
Haha - i feel you. but TBH it used to be so that in the past using `string.Empty` would case a single allocation instead of multiple, but nowadays the compiler fixes this and it doesn't matter.

2022-08-17 11:00 UTC, sommmen commented on src/Serilog.Ui.Web/package-lock.json
>  {
Sure, copied package-lock.json from /dev and pushed that.

2022-08-18 07:34 UTC, followynne commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
For me it's fine either way, I'll leave the choice to you and @mo-esmp 🙂

2022-08-18 07:40 UTC, followynne approved these changes

2022-08-18 08:24 UTC, mo-esmp commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
For injecting the StyleSheet, normally we add it to the header and I don't know if we need to add StyleSheet at the end of body? For JS default choice would be the end of the body and it's better at least add a parameter to the method for adding JS to the head or end of the body.

2022-08-18 09:45 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
> For injecting the StyleSheet, normally we add it to the header and I don't know if we need to add StyleSheet at the end of body?

Stylesheets in the head are loaded in order, the last overwrites the first (hence 'cascading' in CSS). So technically if you want `custom.js` to overwrite the other css files it should be placed at the bottom of the `<head>` so that it could overwrite any default css - i think ill move it to the bottom.

Regarding adding the sheet in the body:
> A <link> element can occur either in the [<head>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head) or [<body>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) element, depending on whether it has a [link type](https://html.spec.whatwg.org/multipage/links.html#body-ok) that is body-ok. For example, the stylesheet link type is body-ok, and therefore <link rel="stylesheet"> is permitted in the body. However, this isn't a good practice to follow; it makes more sense to separate your <link> elements from your body content, putting them in the <head>.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#targetText=A%20element%20can%20occur,is%20permitted%20in%20the%20body

So i'd just place it in the head.

> For JS default choice would be the end of the body and it's better at least add a parameter to the method for adding JS to the head or end of the body.

I still think adding another `%(BodyContent)` and adding the code to replace that is just overhead, with no real 'gain', i feel like this should be kep as KISS as possible.

Additionally i don't think i can add a dummy `<meta>` tag in the body, so i'd have to think of another dummy tag that doesn't show up in the view (comments are removed by the minifier).

@mo-esmp again - doesn't matter much to me, let me know and i'll move the `InjectJavascript(...)` to a `%(BodyContent)` in the index*, or leave as-is.


* Id place it after loading the other scripts, as was suggested.

2022-08-18 10:26 UTC, mo-esmp commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
> @mo-esmp again - doesn't matter much to me, let me know and i'll move the InjectJavascript(...) to a %(BodyContent) in the index*, or leave as-is.

What I meant is that it would be nice if the `InjectJavascript` supports both the head and body.

2022-08-18 13:09 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/SerilogUiOptionBuilderExtensions.cs
> +        public static void InjectStylesheet(this UiOptions options, string path, string media = "screen")
Added.

2022-08-18 13:46 UTC, followynne approved these changes

2022-08-21 19:44 UTC, mo-esmp commented
Hey @sommmen, 
Could you please update the readme file and add descriptions on injecting custom css/js injection, home button, ...?

2022-08-21 19:47 UTC, sommmen commented
> Hey @sommmen, Could you please update the readme file and add descriptions on injecting custom css/js injection, home button, ...?

Will do tomorrow

2022-08-22 08:52 UTC, sommmen commented
> Hey @sommmen, Could you please update the readme file and add descriptions on injecting custom css/js injection, home button, ...?

Done:

![image](https://user-images.githubusercontent.com/8641495/185880360-73d7be43-22c1-4027-bd28-64ab06eede67.png)
![image](https://user-images.githubusercontent.com/8641495/185880435-1d1287ec-683a-4c28-9756-b82836e2bbdb.png)
![image](https://user-images.githubusercontent.com/8641495/185880511-b2d0b578-65a2-4a5c-8918-9317d8374092.png)

2022-08-22 14:05 UTC, mo-esmp commented on src/Serilog.Ui.Web/Extensions/AuthorizationOptions.cs
> +        public bool AlwaysAllowLocalRequests { get; set; } = true;
By default, [middleware](https://github.com/mo-esmp/serilog-ui/blob/a8d3a947ff96f068021af86b9af35ee9d7b605b2/src/Serilog.Ui.Web/SerilogUiMiddleware.cs#L170) allows local request

2022-08-22 14:12 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/AuthorizationOptions.cs
> +        public bool AlwaysAllowLocalRequests { get; set; } = true;
> By default, [middleware](https://github.com/mo-esmp/serilog-ui/blob/a8d3a947ff96f068021af86b9af35ee9d7b605b2/src/Serilog.Ui.Web/SerilogUiMiddleware.cs#L170) allows local request

Could you elaborate? because what you're saying is true and that behaviour has not changed.

``` csharp
if (httpContext.Request.IsLocal() && authOptions.AlwaysAllowLocalRequests)
                return true;
```
https://github.com/mo-esmp/serilog-ui/pull/40/files#diff-b4b11d16bda2405b648052f4d266c459c7789f8b5d426b8987af8d43441b4398R178

2022-08-22 20:38 UTC, mo-esmp commented on src/Serilog.Ui.Web/Extensions/AuthorizationOptions.cs
> +        public bool AlwaysAllowLocalRequests { get; set; } = true;
So that's an option to control auth for local requests, looks good.

2022-08-22 20:41 UTC, sommmen commented on src/Serilog.Ui.Web/Extensions/AuthorizationOptions.cs
> +        public bool AlwaysAllowLocalRequests { get; set; } = true;
👍 can you merge in this pr and make a release or do you need anything else done?

2022-08-23 13:39 UTC, mo-esmp approved these changes

2022-08-23 13:39 UTC, merged

2022-08-25 08:26 UTC, mo-esmp commented
@sommmen new version is released and please upgrade to the version `2.2.0`.